config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                                          Controller#Action
#         root GET    /                                                    pages#home
#   favourites GET    /users/:id/favourites(.:format)                      favourites#index
#              GET    /users/:id/favourites/:board_id(.:format)            favourites#show
#              POST   /users/:id/favourites(.:format)                      favourites#create
#              PATCH  /users/:id/favourites/:board_id/:custom_id(.:format) favourites#update
#              PUT    /users/:id/favourites/:board_id/:custom_id(.:format) favourites#update
#              DELETE /users/:id/favourites/:board_id(.:format)            favourites#destroy
#              POST   /customs/:id/upvotes(.:format)                       upvotes#create
#              DELETE /customs/:id/upvotes(.:format)                       upvotes#destroy
#        users GET    /users(.:format)                                     users#index
#              POST   /users(.:format)                                     users#create
#     new_user GET    /users/new(.:format)                                 users#new
#    edit_user GET    /users/:id/edit(.:format)                            users#edit
#         user GET    /users/:id(.:format)                                 users#show
#              PATCH  /users/:id(.:format)                                 users#update
#              PUT    /users/:id(.:format)                                 users#update
#     toasters GET    /toasters(.:format)                                  toasters#index
#              POST   /toasters(.:format)                                  toasters#create
#  new_toaster GET    /toasters/new(.:format)                              toasters#new
# edit_toaster GET    /toasters/:id/edit(.:format)                         toasters#edit
#      toaster GET    /toasters/:id(.:format)                              toasters#show
#              PATCH  /toasters/:id(.:format)                              toasters#update
#              PUT    /toasters/:id(.:format)                              toasters#update
#              DELETE /toasters/:id(.:format)                              toasters#destroy
#     comments POST   /comments(.:format)                                  comments#create
# edit_comment GET    /comments/:id/edit(.:format)                         comments#edit
#      comment PATCH  /comments/:id(.:format)                              comments#update
#              PUT    /comments/:id(.:format)                              comments#update
#              DELETE /comments/:id(.:format)                              comments#destroy
#      customs POST   /customs(.:format)                                   customs#create
#   new_custom GET    /customs/new(.:format)                               customs#new
#  edit_custom GET    /customs/:id/edit(.:format)                          customs#edit
#       custom GET    /customs/:id(.:format)                               customs#show
#              PATCH  /customs/:id(.:format)                               customs#update
#              PUT    /customs/:id(.:format)                               customs#update
#              DELETE /customs/:id(.:format)                               customs#destroy
#    wallposts POST   /wallposts(.:format)                                 wallposts#create
#        login GET    /login(.:format)                                     session#new
#              POST   /login(.:format)                                     session#create
#       logout DELETE /logout(.:format)                                    session#destroy
# 

Rails.application.routes.draw do

  root :to => "pages#home"

  get "/users/:id/favourites" => "favourites#index", :as => "favourites"
  get "/users/:id/favourites/:board_id" => "favourites#show"
  post "/users/:id/favourites/" => "favourites#create"
  patch "/users/:id/favourites/:board_id/:custom_id" => "favourites#update"
  put "/users/:id/favourites/:board_id/:custom_id" => "favourites#update"
  delete "/users/:id/favourites/:board_id" => "favourites#destroy"
  post "/customs/:id/upvotes" => "upvotes#create"
  delete "/customs/:id/upvotes" => "upvotes#destroy"

  resources :users, :only => [:index, :new, :create, :show, :edit, :update]
  resources :toasters, :only => [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :comments, :only => [:create, :edit, :update, :destroy]
  resources :customs, :only => [:new, :create, :edit, :update, :destroy, :show]
  resources :wallposts, :only => [:create]
  # resources :upvotes, :only => [:create]


  get '/login' => "session#new"
  post '/login' => "session#create"
  delete '/logout' => "session#destroy"
end

app/models/custom.rb
# == Schema Information
#
# Table name: customs
#
#  id          :bigint(8)        not null, primary key
#  name        :text
#  image       :text
#  user_id     :text
#  toaster_id  :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :text
#

class Custom < ApplicationRecord
  belongs_to :user
  belongs_to :toaster
  has_many :wallposts
  has_and_belongs_to_many :favourites
  has_many :upvotes

  validates :image, :presence => true
end

app/controllers/customs_controller.rb
class CustomsController < ApplicationController

  def new
    if @current_user == nil then redirect_to login_path end
    @custom = Custom.new
  end

  def create
    params[:custom][:user_id] = @current_user.id
    if params[:custom][:image].nil?
      params[:custom][:image] = "https://res.cloudinary.com/dyqesnour/image/upload/v1511739515/gen-toaster_fg73fj.jpg"
    else
      cloudinary = Cloudinary::Uploader.upload(params["custom"]["image"], :width => 1000, :height => 1000, :crop => :pad)
      params[:custom][:image] = cloudinary["secure_url"]
    end
    @custom = Custom.new customs_params
    if @custom.save
      redirect_to user_path(@custom.user)
    else
      render :new
    end
  end

  def show
    @custom = Custom.find params[:id]
    @wallpost = Wallpost.new
    @favourite = Favourite.new
  end

  def edit
    @custom = Custom.find params[:id]
    redirect_to toasters_path unless @custom.user == @current_user || @current_user.admin?
  end

  def update
    custom = Custom.find params[:id]
    unless params[:custom][:image].nil?
      cloudinary = Cloudinary::Uploader.upload(params["custom"]["image"], :width => 1000, :height => 1000, :crop => :pad)
      params[:custom][:image] = cloudinary["secure_url"]
    end
    custom.update customs_params
    redirect_to user_path(custom.user)
  end

  def destroy
    custom = Custom.find params[:id]
    custom.destroy
    redirect_to user_path(custom.user)

  end


  private
  def customs_params
    params.require(:custom).permit(:name, :image, :toaster_id, :user_id, :description)
  end
end

app/helpers/customs_helper.rb
module CustomsHelper
end

app/views/customs/edit.html.erb
<h1>EDIT CUSTOM</h1>

<%= form_for @custom, :html => {:multipart => true} do |f| %>


<%= f.label :name %>
<%= f.text_field :name, :required => true %>

<%= f.label "image" %>
<%= f.file_field :image %>

<%= f.label "Description" %>
<%= f.text_area :description %>

<%= f.submit "Add Comment" %>

<% end %>

<small><%= link_to "delete", custom_path(@custom), :method => "delete" %></small>

app/views/customs/new.html.erb
<div class="customform">

<h1>Add a Custom Toaster to the Database</h1>

<%= form_for @custom, :html => {:multipart => true}  do |f| %>

  <%= f.label :name, :class => "block" %>
  <%= f.text_field :name, :required => true, :class => "block" %>

  <%= f.label :image, :class => "block" %>
  <%= f.file_field :image, :class => "block" %>

  <%= f.label :description, :class => "block" %>
  <%= f.text_area :description, size: "50x5", :class => "block" %>

  <%= f.label "Toaster Model", :class => "block" %>
  <%= f.select :toaster_id, Toaster.pluck(:model, :id), :include_blank => true, :class => "block" %>

  <%= link_to "Add New Toaster to Database?", new_toaster_path, :class => "block"  %>

  <%= f.submit "Add the Custom", :class => "block" %>


<% end %>

</div>

app/views/customs/show.html.erb
<div class="container custom-container">


<h1><em><%= @custom.name %></em> created by <a href="/users/<%= @custom.user.id %>"><%= @custom.user.username %></a></h1>

<img src="<%= @custom.image %>" alt="" class="img-thumbnail custom-image">

<h6>Description</h6>
<p><%= @custom.description %></p>

<h4>FAVOURITES</h4>
<% unless @current_user.nil? %>
<a class="fave-link">Add To Favourites</a>
<div class="faves-box hidden">
  <% unless @current_user.favourites.nil? %>
      <% @current_user.favourites.each do |f| %>
        <% unless f.customs.include? @custom %>
          <%= link_to "Add to #{f.name} board", "/users/#{@current_user.id}/favourites/#{f.id}/#{@custom.id}", method: :patch %>
        <% else %>
          <%= link_to "Remove from #{f.name} board", "/users/#{@current_user.id}/favourites/#{f.id}/#{@custom.id}", method: :patch %>
        <% end %>
      <% end %>
  <% end %>

  <h4>Add A New Favourite Board to Your Account</h4>
  <%= form_for @favourite do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, :required => true %>
    <%= f.submit "Create" %>
  <% end %>

</div>
<% else %> <!-- unless no current user -->
<a href="/login">Please login to favourite a custom</a>
<% end %>

<H4>UPVOTES</H4>
<h5><%= @custom.upvotes.length %></h5>
<% unless @current_user.nil? %>
  <% unless @current_user.upvotes.exists?(:custom_id => @custom.id) %>
    <%= link_to "Upvote", "/customs/#{params[:id]}/upvotes", :method => :post %>
  <% else %>
    <%= link_to "Un Upvote", "/customs/#{params[:id]}/upvotes", :method => :delete %>
  <% end %>
<% end %>

<h1>COMMENT WALL</h1>
<div class="comment-wall">
  <% @custom.wallposts.each do |w| %>
    <div class="wallpost">
      <img src="<%= w.user.image %>" alt="profile-picture" class="img-thumbnail">
      <a href="/users/<%= w.user.id %>"><h4><%= w.user.username %></h4></a>
      <p><%= w.message %></p>
      <hr class="seperator2">
    </div>
  <% end %>

</div>

  <div class="combox">
  <h5>Add a Comment</h5>
  <% if @current_user %>
    <%= form_for @wallpost do |f| %>

    <%= f.hidden_field :custom_id, :value => @custom.id %>

    <%= f.text_area :message, :required => true, :class => "block comment-input", size: "50x5" %>

    <%= f.submit "Add Comment", :class => "btn btn-primary submit-button" %>

    <% end %>
  <% else %>
    <h6>Please <a href="/login">Sign in</a> to Leave a Comment</h6>
  <% end %>
  </div>
</div>