config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                                          Controller#Action
#         root GET    /                                                    pages#home
#   favourites GET    /users/:id/favourites(.:format)                      favourites#index
#              GET    /users/:id/favourites/:board_id(.:format)            favourites#show
#              POST   /users/:id/favourites(.:format)                      favourites#create
#              PATCH  /users/:id/favourites/:board_id/:custom_id(.:format) favourites#update
#              PUT    /users/:id/favourites/:board_id/:custom_id(.:format) favourites#update
#              DELETE /users/:id/favourites/:board_id(.:format)            favourites#destroy
#              POST   /customs/:id/upvotes(.:format)                       upvotes#create
#              DELETE /customs/:id/upvotes(.:format)                       upvotes#destroy
#        users GET    /users(.:format)                                     users#index
#              POST   /users(.:format)                                     users#create
#     new_user GET    /users/new(.:format)                                 users#new
#    edit_user GET    /users/:id/edit(.:format)                            users#edit
#         user GET    /users/:id(.:format)                                 users#show
#              PATCH  /users/:id(.:format)                                 users#update
#              PUT    /users/:id(.:format)                                 users#update
#     toasters GET    /toasters(.:format)                                  toasters#index
#              POST   /toasters(.:format)                                  toasters#create
#  new_toaster GET    /toasters/new(.:format)                              toasters#new
# edit_toaster GET    /toasters/:id/edit(.:format)                         toasters#edit
#      toaster GET    /toasters/:id(.:format)                              toasters#show
#              PATCH  /toasters/:id(.:format)                              toasters#update
#              PUT    /toasters/:id(.:format)                              toasters#update
#              DELETE /toasters/:id(.:format)                              toasters#destroy
#     comments POST   /comments(.:format)                                  comments#create
# edit_comment GET    /comments/:id/edit(.:format)                         comments#edit
#      comment PATCH  /comments/:id(.:format)                              comments#update
#              PUT    /comments/:id(.:format)                              comments#update
#              DELETE /comments/:id(.:format)                              comments#destroy
#      customs POST   /customs(.:format)                                   customs#create
#   new_custom GET    /customs/new(.:format)                               customs#new
#  edit_custom GET    /customs/:id/edit(.:format)                          customs#edit
#       custom GET    /customs/:id(.:format)                               customs#show
#              PATCH  /customs/:id(.:format)                               customs#update
#              PUT    /customs/:id(.:format)                               customs#update
#              DELETE /customs/:id(.:format)                               customs#destroy
#    wallposts POST   /wallposts(.:format)                                 wallposts#create
#        login GET    /login(.:format)                                     session#new
#              POST   /login(.:format)                                     session#create
#       logout DELETE /logout(.:format)                                    session#destroy
# 

Rails.application.routes.draw do

  root :to => "pages#home"

  get "/users/:id/favourites" => "favourites#index", :as => "favourites"
  get "/users/:id/favourites/:board_id" => "favourites#show"
  post "/users/:id/favourites/" => "favourites#create"
  patch "/users/:id/favourites/:board_id/:custom_id" => "favourites#update"
  put "/users/:id/favourites/:board_id/:custom_id" => "favourites#update"
  delete "/users/:id/favourites/:board_id" => "favourites#destroy"
  post "/customs/:id/upvotes" => "upvotes#create"
  delete "/customs/:id/upvotes" => "upvotes#destroy"

  resources :users, :only => [:index, :new, :create, :show, :edit, :update]
  resources :toasters, :only => [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :comments, :only => [:create, :edit, :update, :destroy]
  resources :customs, :only => [:new, :create, :edit, :update, :destroy, :show]
  resources :wallposts, :only => [:create]
  # resources :upvotes, :only => [:create]


  get '/login' => "session#new"
  post '/login' => "session#create"
  delete '/logout' => "session#destroy"
end

app/models/toaster.rb
# == Schema Information
#
# Table name: toasters
#
#  id           :bigint(8)        not null, primary key
#  model        :text
#  manufacturer :text
#  year         :integer
#  rating       :float            default(0.0)
#  ratings      :integer          default(0)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :integer
#  image        :text
#  score        :float            default(0.0)
#  description  :text
#

class Toaster < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :collections
  has_many :customs
end

app/controllers/toasters_controller.rb
class ToastersController < ApplicationController

  def index
    @toasters = case params[:sort]
    when nil then Toaster.all.order(model: :asc)
    when "model" then Toaster.all.order(model: :asc)
    when "manufacturer" then Toaster.all.order(manufacturer: :asc)
    when "rating" then Toaster.all.order(score: :desc)
    end
    # @toasters = Toaster.all.sort_by {|t| eval(sortable)}
    # @toasters = Toaster.all.order(sortable: asc )
    # raise 'hell'
  end

  def new
    @toaster = Toaster.new
  end

  def create
    if params[:toaster][:image].nil?
      params[:toaster][:image] = "https://res.cloudinary.com/dyqesnour/image/upload/v1511739515/gen-toaster_fg73fj.jpg"
    else
      cloudinary = Cloudinary::Uploader.upload(params["toaster"]["image"], :width => 1000, :height => 1000, :crop => :pad)
      params[:toaster][:image] = cloudinary["secure_url"]
    end
    params[:toaster][:user_id] = @current_user.id
    @toaster = Toaster.new toaster_params
    if @toaster.save
      redirect_to toasters_path
    else
      render :new
    end
  end

  def show
    @toaster = Toaster.find params[:id]
    @comment = Comment.new
    @comments = @toaster.comments
  end

  def edit
    @toaster = Toaster.find params[:id]
    redirect_to toasters_path unless @toaster.user == @current_user || @current_user.admin?
  end

  def update
    toaster = Toaster.find params[:id]
    unless params[:toaster][:image].nil?
      cloudinary = Cloudinary::Uploader.upload(params["toaster"]["image"], :width => 1000, :height => 1000, :crop => :pad)
      params[:toaster][:image] = cloudinary["secure_url"]
    end
    toaster.update toaster_params
    redirect_to toaster_path(params[:id])
  end

  def destroy
    @toaster = Toaster.find params[:id]
    redirect_to toasters_path unless @toaster.user.id == @current_user || @current_user.admin?
    @toaster.destroy
    redirect_to toasters_path
  end


  private
  def toaster_params
    params.require(:toaster).permit(:model, :manufacturer, :year, :user_id, :image, :description)
  end
end

app/helpers/toasters_helper.rb
module ToastersHelper
end

app/views/toasters/edit.html.erb
<h1>Edit Toaster</h1>

<%= form_for @toaster, :html => {:multipart => true} do |f| %>

  <%= f.label :model %>
  <%= f.text_field :model, :required => true %>

  <%= f.label :manufacturer %>
  <%= f.text_field :manufacturer, :required => true %>

  <%= f.label :year %>
  <%= f.number_field :year %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :image %>
  <%= f.file_field :image %>



  <%= f.submit "Add the Toaster" %>


<% end %>

app/views/toasters/index.html.erb
<div class="index-container">


<div class="herotitle">
  <!-- <div class="toast-title">
    <h1>TOASTER</h1>
  </div> -->
  <div class='toaster-container bounce'>

  <!-- <div class='contain-smoke'>
    <div class='smoke left'></div>
    <div class='smoke right'></div>
    <div class='smoke left'></div>
    <div class='smoke right'></div>
  </div> -->
  <!-- <div class='contain-smoke'>
    <div class='smoke left'></div>
    <div class='smoke right'></div>
    <div class='smoke left'></div>
    <div class='smoke right'></div>
  </div> -->
  <div class='contain-toast bounce2'>
    <div class='crust-bottom'></div>
    <div class='crust'></div>
    <div class='toast bread'></div>
    <div class='toast-bottom bread'></div>
    <div class='crust-bottom front'></div>
    <div class='crust front'></div>
    <div class='toast front bread'></div>
    <div class='toast-bottom front bread'></div>
  </div>
  <div class='contain-toaster'>
    <div class='toaster-back'></div>
    <div class='toaster'></div>
    <div class='base'></div>
    <div class='knob-base'></div>
    <div class='knob'></div>
  </div>
  </div>
</div>



<div class="container index-list">
  <div class="row">
    <div class="col-xs-3 col-xs-offset-2">
      <h4>Model</h4>
    </div>
    <div class="col-xs-3">
      <h4>Manufacturer</h4>
    </div>
    <div class="col-xs-2">
      <h4>Rating</h4>
    </div>
    <div class="col-xs-2">
      <form action="/toasters">
        <label class="sortlabel">Sort By:</label>
        <select class="sortable" name="sort">
          <option value="model" <% if params[:sort] == "model" %> selected <% end %> >Model Name</option>
          <option value="manufacturer" <% if params[:sort] == "manufacturer" %> selected <% end %>>Manufacturer Name</option>
          <option value="rating" <% if params[:sort] == "rating" %> selected <% end %>>Ratings</option>
        </select>
        <button class="sortbutton" hidden>Go</button>
      </form>
    </div>
  </div>
  <hr class="seperator">

<% @toasters.each do |t| %>
    <div class="row">
    <div class="col-xs-1 col-xs-offset-1">
      <img src="<%= t.image %>" alt="toaster-image" class="listimage">
    </div>
    <div class="col-xs-3">
      <a href="<%= toaster_path(t.id) %>">
        <h4><%= t.model %></h4><% unless t.year.nil? %><h6>( <%= t.year %> )</h6><% end %>
      </a>
    </div>
    <div class="col-xs-3">
      <h4><%= t.manufacturer %></h4>
    </div>
    <div class="col-xs-3">
      <h6><% unless t.score == 0 %>
        <div class="smallshowstars">
          <div class="smallgoldstars" style="width: calc(25px * <%= t.score %>)"></div>
        </div>
        <p><%= sprintf('%.2f', t.score ) %></p>
        <% else %>
        Not yet Rated
        <% end %>
      </h6>
    </div>

    <!-- <%= link_to "View Toaster", toaster_path(t.id) %> -->
  </div>
  <hr class="seperator2">
<% end %>
</div>

</div>

app/views/toasters/new.html.erb
<div class="signup-container">

<h1 class='toaster-add-title'>Add a Toaster to the Database</h1>
<p><%= flash[:error] %></p>
<%= form_for @toaster, :html => {:multipart => true} do |f| %>

  <%= f.label :model, :class => "block" %>
  <%= f.text_field :model, :required => true, :class => "block" %>

  <%= f.label :manufacturer %>
  <%= f.text_field :manufacturer, :required => true, :class => "block" %>

  <%= f.label "Year (optional):", :class => "block" %>
  <%= f.number_field :year, :class => "block" %>

  <%= f.label :description, :class => "block" %>
  <%= f.text_area :description, :class => "block", size: "50x10" %>
  <!-- <%= f.hidden_field :user_id, :value => @current_user.id %> -->

  <%= f.label :image, :class => "block" %>
  <%= f.file_field :image, :class => "block" %>

  <%= f.submit "Add the Toaster", :class => "block btn btn-default" %>


<% end %>

</div>

app/views/toasters/show.html.erb
<div class="container toast-container">

  <div class="col-md-4">
    <img src="<%= @toaster.image %>" class="img-thumbnail t-profile" alt="">
    <p class="text-right">Added by <%= link_to @toaster.user.username, user_path(@toaster.user.id) %></p>
    <% unless @current_user.nil? %>
      <% if @current_user == @toaster.user || @current_user.admin %>
        <%= link_to "Edit", edit_toaster_path(@toaster.id) %>
        <%= button_to "Delete Toaster", toaster_path(@toaster.id), :method => "delete" %>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-8 showtoaster">
    <div class="row center">
      <h2><%= @toaster.model %></h2>
    </div>
    <div class="row center">
      <h3>by <%= @toaster.manufacturer %></h3>
    </div>
    <div class="row center">
      <% unless @toaster.score == 0%>
      <div class="showstars">
        <div class="goldstars" style="width: calc(50px * <%= @toaster.score %>)"></div>
      </div>
    </div>
    <div class="row center">
      <h5>( <%= @toaster.score %> )</h5>
      <% else %>
      <h5>Not Yet Rated</h3>
      <% end %>
    </div>
    <% unless @toaster.description.nil? %>
    <div class="row center">
      <h5 style="margin-top: 50px;">Description</h5>
    </div>
    <div class="row center desc-box">
      <p style="padding: 20px;"><%= @toaster.description %></p>
    </div>
    <% end %>
  </div>

  </div>
</div>




<!-- <p>Added by <%= link_to @toaster.user.username, user_path(@toaster.user.id) %></p>
<% if @current_user == @toaster.user %>
<%= link_to "Edit", edit_toaster_path(@toaster.id) %>
<%= button_to "Delete Toaster", toaster_path(@toaster.id), :method => "delete" %>
<% end %> -->

<div class="container">
  <div class="row">

  <div class="col-md-4">

  <h5>Add A Review</h5>
  <% if @current_user %>
    <%= form_for @comment do |f| %>

    <%= f.hidden_field :toaster_id, :value => @toaster.id %>

    <%= f.label :title, :class => "block" %>
    <%= f.text_field :title, :required => true, :class => "block" %>
    <%= f.label "Rating /5", :class => "block" %>
    <%= f.number_field :rating, :min => 1, :max => 5, :class => "block" %>
    <%= f.label "Comment", :class => "block" %>
    <%= f.text_area :body, :required => true, size: "50x5", :class => "block"%>
    <%= f.submit "Add Comment", :class => "btn btn-primary submit-button" %>

    <% end %>
  <% else %>
  <h6>Please <a href="/login">Sign in</a> to Leave a Review</h6>
  <% end %>
  </div>


  <div class="col-md-8">
    <h5>Reviews</h5>
    <div class="commentbox">
      <% @comments.each do |c| %>
        <h4><%= c.title %> <% if c.updated_at != c.created_at %><small><em>- Edited</em></small><% end %></h4>
        <% unless c.rating.nil? %>
          <% (0...c.rating).each do %>
            <%= image_tag "https://res.cloudinary.com/dyqesnour/image/upload/v1511736720/star_bcdkot.png", :class => "stars", :alt => "star" %>
          <% end %>
        <% end %>
        <p><%= c.body %></p>
          <% unless @current_user == nil %>
            <% if c.user == @current_user || @current_user.admin == true %>
              <small><%= link_to "edit", edit_comment_path(c.id) %></small>
            <% end %>
          <% end %>
        <img src="<%= c.user.image %>" alt="profile-image" class="review-image" >
        <small><p style="display: inline-block;"><%= link_to c.user.username, user_path(c.user.id) %></p></small>
        <hr class="seperator2">
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <div class="row">
      <h1 style="margin: 0 auto;">Custom Versions of this Toaster</h1>
    </div>
    <div class="row">
      <div class="toaster-customs">
        <% unless @toaster.customs.empty? %>
          <% @toaster.customs.each do |custom| %>
            <a href="/customs/<%= custom.id %>">
              <div class="toaster-custom" style="background-image: url(<%= custom.image %>)">
                <h3><%= custom.name %></h3>
                <% if custom.user == @current_user %>
                  <a href="/customs/<%= custom.id %>/edit" class="custom-edit">Edit</a>
                <% end %>
              </div>
            </a>
          <% end %>
        <% else %>
          <p>No one has customised this toaster yet!</p>
        <% end %>
        <% unless @current_user.nil? %>
          <a href="/customs/new" style="display: block;" class="custaddlink">Add Your Custom Toaster to Hotbox!</a>
        <% end %>


      </div>
    </div>
  </div>
</div>

</div>