config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                                          Controller#Action
#         root GET    /                                                    pages#home
#   favourites GET    /users/:id/favourites(.:format)                      favourites#index
#              GET    /users/:id/favourites/:board_id(.:format)            favourites#show
#              POST   /users/:id/favourites(.:format)                      favourites#create
#              PATCH  /users/:id/favourites/:board_id/:custom_id(.:format) favourites#update
#              PUT    /users/:id/favourites/:board_id/:custom_id(.:format) favourites#update
#              DELETE /users/:id/favourites/:board_id(.:format)            favourites#destroy
#              POST   /customs/:id/upvotes(.:format)                       upvotes#create
#              DELETE /customs/:id/upvotes(.:format)                       upvotes#destroy
#        users GET    /users(.:format)                                     users#index
#              POST   /users(.:format)                                     users#create
#     new_user GET    /users/new(.:format)                                 users#new
#    edit_user GET    /users/:id/edit(.:format)                            users#edit
#         user GET    /users/:id(.:format)                                 users#show
#              PATCH  /users/:id(.:format)                                 users#update
#              PUT    /users/:id(.:format)                                 users#update
#     toasters GET    /toasters(.:format)                                  toasters#index
#              POST   /toasters(.:format)                                  toasters#create
#  new_toaster GET    /toasters/new(.:format)                              toasters#new
# edit_toaster GET    /toasters/:id/edit(.:format)                         toasters#edit
#      toaster GET    /toasters/:id(.:format)                              toasters#show
#              PATCH  /toasters/:id(.:format)                              toasters#update
#              PUT    /toasters/:id(.:format)                              toasters#update
#              DELETE /toasters/:id(.:format)                              toasters#destroy
#     comments POST   /comments(.:format)                                  comments#create
# edit_comment GET    /comments/:id/edit(.:format)                         comments#edit
#      comment PATCH  /comments/:id(.:format)                              comments#update
#              PUT    /comments/:id(.:format)                              comments#update
#              DELETE /comments/:id(.:format)                              comments#destroy
#      customs POST   /customs(.:format)                                   customs#create
#   new_custom GET    /customs/new(.:format)                               customs#new
#  edit_custom GET    /customs/:id/edit(.:format)                          customs#edit
#       custom GET    /customs/:id(.:format)                               customs#show
#              PATCH  /customs/:id(.:format)                               customs#update
#              PUT    /customs/:id(.:format)                               customs#update
#              DELETE /customs/:id(.:format)                               customs#destroy
#    wallposts POST   /wallposts(.:format)                                 wallposts#create
#        login GET    /login(.:format)                                     session#new
#              POST   /login(.:format)                                     session#create
#       logout DELETE /logout(.:format)                                    session#destroy
# 

Rails.application.routes.draw do

  root :to => "pages#home"

  get "/users/:id/favourites" => "favourites#index", :as => "favourites"
  get "/users/:id/favourites/:board_id" => "favourites#show"
  post "/users/:id/favourites/" => "favourites#create"
  patch "/users/:id/favourites/:board_id/:custom_id" => "favourites#update"
  put "/users/:id/favourites/:board_id/:custom_id" => "favourites#update"
  delete "/users/:id/favourites/:board_id" => "favourites#destroy"
  post "/customs/:id/upvotes" => "upvotes#create"
  delete "/customs/:id/upvotes" => "upvotes#destroy"

  resources :users, :only => [:index, :new, :create, :show, :edit, :update]
  resources :toasters, :only => [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :comments, :only => [:create, :edit, :update, :destroy]
  resources :customs, :only => [:new, :create, :edit, :update, :destroy, :show]
  resources :wallposts, :only => [:create]
  # resources :upvotes, :only => [:create]


  get '/login' => "session#new"
  post '/login' => "session#create"
  delete '/logout' => "session#destroy"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toasty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <ul class="nav nav-pills nav-justified">
      <li class="nav item">
        <%= link_to "Home", root_path, :class => "nav-link" %>
      </li>
      <li class="nav item">
        <%= link_to "Toasters", toasters_path, :class => "nav-link" %>
      </li>
      <% if @current_user.present? %>

      <% if @current_user.admin? %>
      <li class="nav item">
        <%= link_to "All Users", users_path, :class => "nav-link" %>
      </li>
      <% end %>
      <li class="nav item">
        <%= link_to "Add A Toaster", new_toaster_path, :class => "nav-link" %>
      </li>

      <li role="presentation" class="dropdown nav item">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          <%= @current_user.username %> <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" style="width: 100%;">
          <li>
            <a href="<%= user_path(@current_user.id) %>" class="text-center"><img src="<%= @current_user.image %>" alt="" class="menu-image">View Profile</a>
          </li>
          <li>
            <a href="/users/<%= @current_user.id %>/favourites" class="text-center">Favourites</a>
          </li>
          <li>
            <%= link_to "Sign Out of #{@current_user.email}", logout_path, :class => "text-center", :method => "delete" %>
          </li>
        </ul>
      </li>
      <% else %> <!--- IF CURRENT USER PRESENT --->
      <li class="nav item">
        <%= link_to "Sign Up", new_user_path, :class => "nav-link" %>
      </li>
      <li class="nav item">
        <%= link_to "Sign In", login_path, :class => "nav-link" %>
      </li>
      <% end %> <!--- IF NO ONE IS LOGGED IN --->
    </ul>

    <%= yield %>


    <footer>
      <h6 class="text-right">Created by <a href="https://www.github.com/chriswillphoto">Christopher Nekich</a> 2017</h6>
    </footer>
  </body>
</html>